### Logar e pegar o token
# @name login
POST {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password_hash": "senha_"
}

### Listar todos os agendamentos
GET {{baseURL}}/dashboard
Authorization: Bearer {{login.response.body.data.token}}

### Listar todos os agendamentos
GET {{baseURL}}/dashboard?professional_id=1
Authorization: Bearer {{login.response.body.data.token}}

### Listar todos os agendamentos
GET {{baseURL}}/dashboard?professional_id=1&status_id=2
Authorization: Bearer {{login.response.body.data.token}}

### Listar todos os agendamentos
GET {{baseURL}}/dashboard?professional_id=1&status_id=2&user_id=3
Authorization: Bearer {{login.response.body.data.token}}

### Listar todos os agendamentos
GET {{baseURL}}/dashboard?professional_id=1&status_id=2&user_id=3&start=2025-01-01
Authorization: Bearer {{login.response.body.data.token}}

### Listar todos os agendamentos
GET {{baseURL}}/dashboard?professional_id=1&status_id=2&user_id=3&start=2025-01-01&end=2026-10-01
Authorization: Bearer {{login.response.body.data.token}}
