# Senha para o login (a inserção do usuário retorna encriptado)
@password_hash = $3nh@_TESTE

# ==========================================
# CENÁRIOS DE SUCESSO (Papel 1 - profissional)
# ==========================================

### Criar um novo usuário
# @name user
POST {{baseURL}}/users
Content-Type: application/json

{
    "name": "Profissional teste",
    "email": "profissional_teste@example.com",
    "password_hash": "{{password_hash}}",
    "role_id": 2
}

### Logar e pegar o token
# @name login
POST {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "{{user.response.body.data.email}}",
    "password_hash": "{{password_hash}}"
}

### Criar um novo profissional vinculado ao usuario
# @name professional
POST {{baseURL}}/professionals
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Profissional teste",
    "speciality_id": 1,
    "phone": "(54) 99999-9999",
    "active": 1
}

# ==========================================
# ROTAS DE CRIAÇÃO - CREATE
# ==========================================

### FAZER: a proibição
### FORBIDDEN/UNAUTHORIZED: Criar um novo profissional com sucesso
# Sem o atributo "active" (o padrão é 1, ou seja, ativo)
# @name professional_create
POST {{baseURL}}/professionals
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Profissional teste para agendamentos",
    "speciality_id": 1,
    "phone": "(54) 99999-9999"
}

# FAZER: a proibição
### FORBIDDEN/UNAUTHORIZED: Criar um novo usuário
# @name client_create
POST {{baseURL}}/users
Content-Type: application/json

{
    "name": "Cliente teste para agendamentos",
    "email": "cliente_teste_agendamentos@example.com",
    "password_hash": "{{password_hash}}",
    "role_id": 1
}

### Criar um novo serviço com sucesso
# @name service_create
POST {{baseURL}}/services
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Tipo de serviço teste para agendamentos 2",
    "area_id": 1,
    "min_duration": 30,
    "price": 50.00
}

### Criar um novo horário com sucesso
# @name works_create
POST {{baseURL}}/works
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "professional_id": {{professional.response.body.data.id}},
    "weekday": 1,
    "start_hour": "09:00",
    "end_hour": "11:00"
}

### Criar um segundo novo horário com sucesso
# @name works_create_2
POST {{baseURL}}/works
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "professional_id": {{professional.response.body.data.id}},
    "weekday": 2,
    "start_hour": "11:00",
    "end_hour": "13:00"
}

### Criar um terceiro novo horário com sucesso
# @name works_create_3
POST {{baseURL}}/works
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "professional_id": {{professional.response.body.data.id}},
    "weekday": 3,
    "start_hour": "13:00",
    "end_hour": "15:00"
}

### Criar um novo bloqueio de horário com sucesso
# @name block_create
POST {{baseURL}}/blocks
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "professional_id": {{professional.response.body.data.id}},
    "start": "2040-01-01 00:00",
    "end": "2040-01-31 23:59",
    "reason": "Bloqueio teste - janeiro de 2040"
}

### Criar um segundo novo bloqueio de horário com sucesso
# @name block_create_2
POST {{baseURL}}/blocks
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "professional_id": {{professional.response.body.data.id}},
    "start": "2040-02-01 00:00",
    "end": "2040-02-28 23:59",
    "reason": "Bloqueio teste - fevereiro de 2040"
}

### FAZER: a proibição (mesmo usuário)
### FORBIDDEN/UNAUTHORIZED: Criar um novo agendamento com sucesso
# @name schedule_create
POST {{baseURL}}/schedules
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "user_id": {{user.response.body.data.id}},
    "professional_id": {{professional.response.body.data.id}},
    "service_id": {{service_create.response.body.data.id}},
    "start_date_hour": "2040-07-20 10:00:00",
    "end_date_hour": "2040-07-20 11:30:00"
}

### FAZER: a proibição (mesmo usuário)
### FORBIDDEN/UNAUTHORIZED: Criar um segundo novo agendamento com sucesso
# @name schedule_create_2
POST {{baseURL}}/schedules
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "user_id": {{user.response.body.data.id}},
    "professional_id": {{professional.response.body.data.id}},
    "service_id": {{service_create.response.body.data.id}},
    "start_date_hour": "2041-08-20 10:00:00",
    "end_date_hour": "2041-08-20 11:30:00"
}

# ==========================================
# VISUALIZAR RESULTADOS ATÉ ENTÃO (READ)
# ==========================================

### Listar bloqueios de horário pelo id do profissional
GET {{baseURL}}/blocks?professional_id={{professional.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar bloqueio de horário pelo id
GET {{baseURL}}/blocks/{{block_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### FAZER: a permissão
### Listar horários do profissional pelo seu id
GET {{baseURL}}/works?professional_id={{professional.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar horários do profissional pelo id do horário
GET {{baseURL}}/works/{{works_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar agendamentos pelo id do profissional
GET {{baseURL}}/schedules?professional_id={{professional.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar agendamento com id específico
GET {{baseURL}}/schedules/{{schedule_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar serviço com id específico
GET {{baseURL}}/services/{{service_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar usuário com id específico
GET {{baseURL}}/users/{{user.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar profissional por id 
GET {{baseURL}}/professionals/{{professional.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

# ==========================================
# ROTAS DE ALTERAÇÃO - UPDATE
# ==========================================

### Atualizar-se (profissional existente)
# @name professional_update
PUT {{baseURL}}/professionals/{{professional.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Profissional teste atualizado",
    "speciality_id": 2,
    "phone": "(54) 88888-8888",
    "active": 1
}

### FORBIDDEN/UNAUTHORIZED: Atualizar um (outro) profissional existente
# @name professional_create_update
PUT {{baseURL}}/professionals/{{professional_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Profissional teste para agendamento atualizado",
    "speciality_id": 2,
    "phone": "(54) 88888-8888",
    "active": 1
}

### FORBIDDEN/UNAUTHORIZED: Atualizar cliente
# @name client_update
PUT {{baseURL}}/users/{{client_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Cliente teste atualizado",
    "email": "cliente_teste@example.com",
    "password_hash": "{{password_hash}}",
    "role_id": 1
}

### Atualizar o próprio usuário 
# @name user_update
PUT {{baseURL}}/users/{{user.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Profissional teste atualizado",
    "email": "profissional_teste@example.com",
    "password_hash": "{{password_hash}}",
    "role_id": 2
}

### Atualizar um serviço existente
# @name service_update
PUT {{baseURL}}/services/{{service_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "name": "Tipo de serviço teste para agendamentos atualizado",
    "area_id": 2,
    "min_duration": 45,
    "price": 60.00
}

### Atualizar um horário existente
# @name works_update
PUT {{baseURL}}/works/{{works_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "professional_id": {{professional_update.response.body.data.id}},
    "weekday": 3,
    "start_hour": "09:30",
    "end_hour": "12:00"
}

### Atualizar um bloqueio de horário existente
# @name block_update
PUT {{baseURL}}/blocks/{{block_create.response.body.data.id}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
    "professional_id": {{professional_update.response.body.data.id}},
    "start": "2050-01-01 10:00",
    "end": "2050-02-28 23:59",
    "reason": "Bloqueio atualizado para janeiro e fevereiro"
}

### Atualizar um agendamento existente
# @name schedule_update
PUT {{baseURL}}/schedules/{{schedule_create.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{
    "user_id": {{user_update.response.body.data.id}},
    "professional_id": {{professional_update.response.body.data.id}},
    "service_id": {{service_update.response.body.data.id}},
    "status_id": 2,
    "start_date_hour": "2050-07-31 20:00:00",
    "end_date_hour": "2050-07-31 21:30:00"
}

# ==========================================
# VISUALIZAR RESULTADOS ATÉ ENTÃO (READ)
# ==========================================

### Listar bloqueios de horário pelo id do profissional
GET {{baseURL}}/blocks?professional_id={{professional_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar bloqueio de horário pelo id
GET {{baseURL}}/blocks/{{block_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### FAZER: a permissão
### Listar horários do profissional pelo seu id
GET {{baseURL}}/works?professional_id={{professional_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar horários do profissional pelo id do horário
GET {{baseURL}}/works/{{works_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar agendamentos pelo id do profissional
GET {{baseURL}}/schedules?professional_id={{professional_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar agendamento com id específico
GET {{baseURL}}/schedules/{{schedule_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar serviço com id específico
GET {{baseURL}}/services/{{service_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar próprio usuário com id específico
GET {{baseURL}}/users/{{user_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar próprio profissional por id 
GET {{baseURL}}/professionals/{{professional_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### FAZER: a proibição
### FORBIDDEN/UNAUTHORIZED: Listar outro profissional por id 
GET {{baseURL}}/professionals/{{professional_create_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### FAZER: a proibição
### FORBIDDEN/UNAUTHORIZED: Listar cliente por id 
GET {{baseURL}}/users/{{client_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

# ==========================================
# ROTA DE ALTERAÇÃO - UPDATE - status
# ==========================================

### Atualizar apenas o status 
### de um agendamento existente
# @name schedule_status_update
PATCH {{baseURL}}/schedules/{{schedule_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}
Content-Type: application/json

{ 
    "status_id": 3 
}

# ==========================================
# VISUALIZAR RESULTADOS ATÉ ENTÃO (READ)
# ==========================================

### Listar agendamentos pelo id do profissional
GET {{baseURL}}/schedules?professional_id={{professional_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### Listar agendamento com id específico
GET {{baseURL}}/schedules/{{schedule_status_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

# ==========================================
# ROTAS DE EXCLUSÃO - DELETE (admin X profissional)
# ==========================================

### Logar como admin para poder excluir
# @name login_admin
POST {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password_hash": "senha_"
}

### FORBIDDEN/UNAUTHORIZED (profissional): Deletar um agendamento existente
DELETE {{baseURL}}/schedules/{{schedule_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### (admin): Deletar um agendamento existente
DELETE {{baseURL}}/schedules/{{schedule_update.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### (admin): Deletar agendamento 2
DELETE {{baseURL}}/schedules/{{schedule_create_2.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### FAZER: a proibição
### FORBIDDEN/UNAUTHORIZED (profissional): Deletar um usuário existente - cliente
DELETE {{baseURL}}/users/{{client_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### (admin): Deletar um usuário existente - cliente
DELETE {{baseURL}}/users/{{client_update.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### (profissional): Deletar-se (usuário existente)
# É possível enquanto durar a seção
# FAZER: Mas deve ser proibido se for o mesmo usuário
DELETE {{baseURL}}/users/{{user_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### FAZER: a permissão?
### (profissional): Deletar um bloqueio de horário existente
DELETE {{baseURL}}/blocks/{{block_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### (admin): Deletar um bloqueio de horário existente
DELETE {{baseURL}}/blocks/{{block_update.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### (admin): Deletar bloqueio 2
DELETE {{baseURL}}/blocks/{{block_create_2.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### FAZER: a permissão
### (profissional): Deletar um horário existente
DELETE {{baseURL}}/works/{{works_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### (admin): Deletar um horário existente
DELETE {{baseURL}}/works/{{works_update.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### (admin): Deletar um horário existente
DELETE {{baseURL}}/works/{{works_create_2.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### (admin): Deletar um horário existente
DELETE {{baseURL}}/works/{{works_create_3.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### (profissional): Deletar um serviço existente
DELETE {{baseURL}}/services/{{service_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### (admin): Deletar um serviço existente
DELETE {{baseURL}}/services/{{service_update.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### FAZER: a permissão
### (profissional): Deletar-se (profissional existente)
DELETE {{baseURL}}/professionals/{{professional_update.response.body.data.id}}
Authorization: Bearer {{login.response.body.data.token}}

### (admin): Deletar profissional (logado)
DELETE {{baseURL}}/professionals/{{professional_update.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

### (admin): Deletar profissional (teste para agendamento)
DELETE {{baseURL}}/professionals/{{professional_create_update.response.body.data.id}}
Authorization: Bearer {{login_admin.response.body.data.token}}

# ==========================================
# VISUALIZAR RESULTADOS ATÉ ENTÃO (READ)
# ==========================================

### Listar todos os agendamentos
GET {{baseURL}}/schedules
Authorization: Bearer {{login_admin.response.body.data.token}}

### Listar todos os usuários
GET {{baseURL}}/users
Authorization: Bearer {{login_admin.response.body.data.token}}

### Listar todos os bloqueios de horário
GET {{baseURL}}/blocks
Authorization: Bearer {{login_admin.response.body.data.token}}

### Listar todos os horários
GET {{baseURL}}/works
Authorization: Bearer {{login_admin.response.body.data.token}}

### Listar todos os serviços
GET {{baseURL}}/services
Authorization: Bearer {{login_admin.response.body.data.token}}

### Listar todos os profissionais
GET {{baseURL}}/professionals
Authorization: Bearer {{login_admin.response.body.data.token}}